### ISSUE TITLE
Changes to WAIT status

### ISSUE THREAD

**Issue by simon-anders** [anders-biostat/covid-test-web-site#164]
At the moment, our status codes are as documented in /doc/status .

However, that diagram is wrong in two respect:
- The WAIT-LONG message was never implemented
- It does not explain LAMP-FAILED.

Furthermore, there are two cases not properly represented in this scheme:

#### LAMP repeat

When LAMP analysis fails to give a result for a sample, the lab can make three decisions: 
- send the sample for PCR. In this case, they set the status LAMPINC using Sveta's tool.
- keep the sample for another try with LAMP on the next day. In this case, they set the status WAIT
- give up on the sample and decide to not try again. This is represented by the status LAMPFAIL

Hence, status WAIT had a double meaning:
- *Before* starting an analysis, the lab scans all received samples and uses the batch status setting form to set status WAIT for all these samples in order to indicate that they have been received.
- *After* the analysis, if the lab team decides to keep a sample to run LAMP on it again the next day, they set WAIT once more. (The other possible status values that can be assigned to a sample after LAMP analysis are LAMPNEG, LAMPINC, LAMPPOS, and LAMPFAIL)

I suggest to retire (deprecate) the WAIT status and replace it with two new statuses:
- RCVD: Sample has been received in the LAMP lab.
- LAMPREP: LAMP analysis for with sample was inconclusive, and sample has been sceduled for repeat of LAMP analysis.

#### LAMPPOS without PCR

Our standard procedure at the moment is to sent samples with inconclusive or positive results for PCR. This is why LAMPPOS and LAMPINC are "intermediate states" (no double border in diagram). A sample with these status values should be considered as still in progress, and by asking for all samples with status LAMPPOS and LAMPINC but not PCRPOS or PCRNEG, we can get all samples waiting for PCR.

However, sometimes, a sample is positive in LAMP but it is decided to not sent it for PCR (e.g., because it was an internal experimental sample, or because it was from a subject known to be positive). We need a way to mark these samples.

Furthermore, it has happened that people forgot to sent samples for PCR. Therefore, it would be good to document that this has been done.

Hence, I suggest to add two new status values: PCRSENT (sent for PCR), PCRNONE (no PCR intended)

##### Summary: New flow

Therefore, we get the following new flow of status values

1. *before LAMP analysis*: All incoming samples get scanned, and the status RCVD is set.

2. *after LAMP analysis*: For each analysed sample, one of the following status values is set:
- LAMPNEG: no signal seen; result is clearly negative
  - Next step: None. This is a final state, no further processing needed.
- LAMPPOS: strong singal seen; result is clearly positive 
  - Standard next step: Sent for PCR for verification
- LAMPINC: weak or ambiguous signal seen; result is inconclusive but could be positive
  - Standard next step: Sent for PCR 
- LAMPREP: failed controls or other sign of failed reaction; LAMP analysis should be repeated on next day
  - Standard next step: repeat LAMP analysis   
- LAMPFAILED: reaction failed, sample cannot be recovered (or analysis will not be repeated for other reasons)
  - This is a final state; the sample will not be precessed any further

3. *sending samples for PCR*: Somebody in the lab gathers all LAMPPOS and LAMPINC samples, fills in forms for sending the samples to the Virology lab for PCR and makes a list of the samples's barcodes. Then, he/she brings the samples to Virology and, upon returning, sets status PCRSENT for all these barcodes.

If there are any LAMPPOS or LAMPINC samples, for which it has been decided that they should not be sent for PCR, the lab team manually sets the status PCRNONE for these sample (and preferably adds a comment, why the sample is not sent for PCR).

4. **after receiving a PCR result**: Whenever we receive a PCR result from Virology, somebody has to set the status PCRPOS or PCRNEG for this sample.

5. **DB queries to check for forgotten samples**: At least every other day, we should do the following two queries to the database:

- *List all samples for which the status value LAMPPOS or LAMPINC has been set at some point but none of the status values staring with PCR has been set afterwards*. This gives a list of all samples which are waiting to be sent for PCR.

- *List all samples for which the status *PCRSENT* has been set with a time stamp earlier than 24 hours before current time, and for which neither PCRPOS or PCRNEG is set.* This is a list of samples for which a report from virology with a PCR result is overdue.

##### Next steps

@michaelknop2, @Bobby-1411, Matthias M, Victoria: Please comment if this makes sense to you.

@alexey0308, @ethylomat, @leonard-hacker: Who would be interested in taking on this task?

**Comment by matthiasmeurer** [comment]
At the moment we are never using the LAMPFAILED status. Even if the LAMP failed 2x (bead contaminations, Zika negative, robotic problems), we set it in Svetas tool on "repeat" which gives it the "WAIT" status and we pass it on to diagnostics for qPCR. I would not give it the status "LAMPINC", since this triggers the message, that we received an inconclusive LAMP result, which makes the people nervous. Maybe we should set it to "LAMPFAILED" and show a message, that it was not possible to analyze the sample with LAMP and that we give it to qPCR. If the qPCR failed also afterwards, we might need another status called "PCRFAILED".

**Comment by simon-anders** [comment]
The LAMFAILED status is used extensively by EMBL, as they don't repeat failed samples.

**Comment by michaelknop2** [comment]
to know .. I wil have a chat with Valdimir … will discuss this

_________________________________

Michael Knop
Ingrimstr. 12
69117 Heidelberg
+49 6221 455463
+49 152 54756440
michael.knop2@googlemail.com

_________________________________

Prof. Dr. rer. nat. Michael Knop
Zentrum für Molekulare Biologie der
Universität Heidelberg
Im Neuenheimer Feld 282
D-69120 Heidelberg
Germany
Tel.: +49-6221 423411
Mobil.:  +49-152 54756440
m.knop@zmbh.uni-heidelberg.de
www.knoplab.de
_________________________________
