### ISSUE TITLE
Text Anpassung auf result page LAMPREPEAT

### ISSUE THREAD

**Issue by matthiasmeurer** [anders-biostat/covid-test-web-site#198]
Der Text sollte beinhalten, dass der fehlgeschlagene Test am nächsten Labortag wiederholt wird. Labortage sind Montag-Freitag:

"Technische Probleme

Leider ist es bei Ihrer Probe zu einem technischen Problem gekommen, so dass wir die Analyse Ihrer Probe nochmals am nächsten Labortag (Mo - Fr) wiederholen müssen.

Solche technischen Problem sind selten, kommen aber vor. Es tut uns leid und wir bitten Sie am Nachmittag des nächsten Labortages noch einmal den Status zu prüfen.

Wenn Sie Fragen dazu haben, schreiben Sie uns bitte: info@coronatest-hd.de

Bleiben Sie dran, wir tun unser Bestes."

Dieser Text in Verbindung mit einem Time Stamp sollte für Klarheit sorgen.

**Comment by AMueller92** [comment]
@matthiasmeurer schaue ich mir an
