### ISSUE TITLE
News box on landing page

### ISSUE THREAD

**Issue by simon-anders** [anders-biostat/covid-test-web-site#204]
We need a way of displaying news below the three buttons on the landing page.

One way might be to have table  of "news items", with three columns: the news text (as HTML text, to be put into a <li>), a date, and a flag whether the news is still "new". On the landing page, below the buttons, we put a (nicely styled) <ul> (or a <table> or whatever looks good in semantic ui), that lists all items marked as "new". And a link to the "news archive", where you get all the news item using some (perhaps paged) table view. I suppose semantic ui has readymade styles for that.

**Comment by AMueller92** [comment]
Closing this issue @simon-anders
