### ISSUE TITLE
Kommentar Feld  bitte dringend ändern 

### ISSUE THREAD

**Issue by michaelknop2** [anders-biostat/covid-test-web-site#219]
Beim Setzten des Status einer Probe gibt es ein Kommentar Feld. Der Text dort wird angezeigt, wenn man MESSAGE wählt. Ansonsten ist der Text dort drin nur als Kommentar für den Operator da. Das ist sehr verwirrend. Bitte zwei Kommentarfelder machen, eines für Text der zusammen mit dem Text des jeweiligen Status dem Teilnehmer bei der Abfrage angezeigt wird (Kommentar - shown to participant), und ein Kommentar Feld für interne Informationen zur Probe (Kommentar - Intern information)

**Comment by simon-anders** [comment]
Duplicate of #170
