### ISSUE TITLE
PCRSENT - Text fehlt? URGENT issue?

### ISSUE THREAD

**Issue by michaelknop2** [anders-biostat/covid-test-web-site#220]
für den Status PCRSENT gibt im directory public/pages keinen Text. Was wird angezeigt? Ds ist ein kritisches Feld, weil alle Probanden die Positiv sind dieses Resultat angezeigt kriegen, oder nicht?

**Comment by simon-anders** [comment]
hat sich erledigt

**Comment by AMueller92** [comment]
Hi @michaelknop2 richtig für PCRSENT gibt es kein Template. Das ist so geregelt das PCRSENT wie ein INFO status gehandhabt wird. Das bedeutet dass die Probanden immer den letzten öffentlichen Status angezeigt bekommen. War jemand vor dem Status PCRSENT beispielweise LAMPPOS, dann wird er das LAMPPOS template angezeigt bekommen.
