### ISSUE TITLE
mobila layout

### ISSUE THREAD

**Issue by Bobby-1411** [anders-biostat/covid-test-web-site#23]
This page is not optimized for smartphone screens.#, the buttons are going over the edge.

Also clicking the menu button (3 horizontal bars), upper right, does not lead anywhere.

In the browser, clicking "impressum" leads to 404

**Comment by herbstk** [comment]
I can confirm. I can't click on the menu on my mobile phone except I use the desktop mode. The explanation text on the next site is too narrow. One has to scroll left and right to confirm one's data entry.
