### ISSUE TITLE
Backup of data/

### ISSUE THREAD

**Issue by simon-anders** [anders-biostat/covid-test-web-site#37]
We need to back up the collected data, especially the subjects.csv file. Perhaps, we can make a cron job to copy it to SDS at regular intervals.

**Comment by Fereydoonthr** [comment]
So he sent me this page:
https://www.digitalocean.com/community/tutorials/how-to-configure-a-linux-service-to-start-automatically-after-a-crash-or-reboot-part-1-practical-examples
