### ISSUE TITLE
Rename all results page to have a consistent naming scheme

### ISSUE THREAD

**Issue by simon-anders** [anders-biostat/covid-test-web-site#46]
All pages that contain a result should have the filename "result-TAG.html", where TAG is the same TAG that is also used in the results.txt file.

Let's use the following tags:

"neg": The LAMP test was negative
"inconcl": The LAMP test was inconclusive, sample waiting for PCR
"probpos": The LAMP test was positive, sample waiting for PCR
"pos": The LAMP test was non-negative, the PCR test was positive, and the Gesundheitsamt was or will be notified
"failed": The LAMP test failed and will not be repeated
"wait": The LAMP test was not yet performed due to lack of capacity

**Comment by simon-anders** [comment]
Now we have to change the results.txt file (and the code checking it) in order to make the codes used there in sync with the tags

**Comment by Fereydoonthr** [comment]
Retrospectively or from now on?
