### ISSUE TITLE
video streaming

### ISSUE THREAD

**Issue by simon-anders** [anders-biostat/covid-test-web-site#6]
We cannot link to a Youtube video as we do not want advertisement. Please find out how to stream the video from our server.

**Comment by Fereydoonthr** [comment]
We need to have the video on the server the rest is straight forward. I should just need to change src attribute to the video file on the server.

**Comment by simon-anders** [comment]
ok, then let's put some random short video on the server and try it out

**Comment by Fereydoonthr** [comment]
I have just upload a sample video.
