### ISSUE TITLE
statuses and result pages

### ISSUE THREAD

**Issue by simon-anders** [anders-biostat/covid-test-web-site#74]
@ethylomat: 
Haben wir schon eine genaue Definiton des Mappings von Sample-Status zu Erbenis-Seite?

Ich vermute, es läuft so: 
- Der jeweils neueste Event, der ein echter Status (also nicht INFO) ist, zählt, und die Webseite test-STATUS.html wird dann angezeigt.
- Beim Status WAIT wird entweder test-WAIT.html oder test-LONG_WAIT.html angezeigt, je nachdem ob der Status jüner oder älter als 24 Stunden ist.

Folgendes ist mir noch nicht klar:
- Gibt es einen Status bzw ein Event RECEIVED, der angibt, ob die Probe im Labor eingegangen und gescannt wurde? Gibt es überhaput einen Status WAIT? Oder sollten wir die test-WAIT.html in test-RECEIVED.html umbenennen und test-WAIT_LONG.html zu test-RECEIVED_DELAYED.html?
- Wenn es einen Even RECEIVED gibt, dann kann ein Sample auch registriert aber noch nicht eingegangen sein. Da sollte dann eine Seite test-NOT_RECEIVED.html (oder so?) angezeigt werden.
- Was genau ist der Unterschied zwischen test-LAMPFAIL.html, test-UNDEF.html und test-ERROR.html? WWann wird was angezeigt?

Im Moment haben wir folgende Statuse:
- PRINTED
- RECEIVED (haben wir das?)
- LAMP_NEG, LAMP_INC, LAMP_POS, LAMP_FAIL (Resultate des LAMP-Tests)
- PCR_NEG, PCR_POS (Resultate der Validation-PCR).

Außerdem sollten wir noch folgende Events loggen, die keine Status-Changes sind:
- sample registered
- sample sent for PCR
- result queried
- decision made to not sent sample for PCR
- data manually changed (in admin interface) [Können wir das automatisch loggen?]
Wie machen wir das?

Und schließlich haben wir noch den Spezialfall, das ein Sample Status LAMP_POS oder LAMP_INC hat, aber nicht zu PCR geschickt wird (Non-Status-Event "decision made to not sent sample for PCR") für das die angezeigte Seite geändert werden muss. Vielleichjt wäre es am einfachsten, in diesem Fall einen Status LAMP_INC_NO_PCR oder LAMP_POS_NO_PCR zu setzen. Das sollte nur passieren, wenn der Proband uns bekannt ist.

Comments?

**Comment by ethylomat** [comment]
Ersteres ist korrekt, es wird das letzte Event betrachtet und manuell mit den Templates gemappt. Generell ist es da wenig sinnvoll die Templates automatisch zu bestimmen beispiel:

def status_page(STATUS):
    return "test-" + STATUS + ".html"

Die entsprechende Implementation ist in der Funktion `render_status()` in der views_public.py. In dieser Form würde ich weiterhin gerne die Statusmeldung darstellen. 

Generell ist WAIT der Status, den eine Probe bekommt, wenn sie das erste mal im Labor registriert wurde. Hier würde ich auch einfach bleiben, um nicht überall alles ändern zu müssen (insbesondere damit auch die Dokumentation konsistent bleibt) Vergleiche status.md im doc Ordner.

Weitere Status würde ich generell nur anlegen, wenn wir diese überhaupt (insbesondere mit den bisherigen Daten) konsistent führen können. Insbesondere würde ich solche Änderungen erst durchführen wollen, wenn für den Code ausreichend tests existieren. Falls nämlich dadurch irgendwas kaputt geht wäre es wichtig dies festzustellen. Dies können wir nur mit enstsprechenden automatisierten tests machen.

Der Status NOT_RECEIVED macht aus meiner Sicht wenig sinn, weil alle Proben != RECEIVED not received sind. Es macht aus meiner Sicht wenig Sinn da zu tief zu differenzieren insbesondere weil unser Laborprozess garnicht so kleinteilig den Status verfolgt. Die Status SEND_TO_PCR würden auch zusätzliche Arbeitsschritte für das Labor bedeuten (parallel zu den vorhandenen Prozessen mit dem Klinikum etc.) das sollte man (falls noch nicht der Fall) genau absprechen. Insbesondere wäre es wichtig, dass es konsistent geführt wird, weil es sonst keinen Mehrwert bringt.

Daten würde ich ungern im Admin-Interface ändern lassen. Hier ist es einfach zu fehlerträchtig (hier gabs ja generell auch berechtigte Bedenken von Michael, dass jegliche Änderungen sehr fehlerträchtig sein können und wir bestenfalls möglichst viele Schnittstellen standardisieren. Hier sollten wir entsprechende Prozesse in den Lab-Views anlegen, die auch den Autor loggen. Die Administrationsoberfläche sollten wir eigentlich nie aufrufen müssen (außer um zu schauen, ob alles funktioniert).

Das Aussortieren von Samples, die nicht zur PCR geschickt werden halte ich persönlich für eine möglicherweise fehlerträchtige Entscheidung, was die Qualität der wissenschaftlichen Daten über den LAMP-Test angeht (also aus wissenschaftlicher Sicht, da möglicherweise ein sampling bias auftritt). Aber falls man das beibehalten möchte (gibt ja auch gute Gründe dafür) müsste man diskutieren auf welcher Ebene wir das implementieren wollen. Es wäre ja auch denkbar, dass das einfach als Excel-Tabelle geführt wird (und da entschieden wird).

Also zusammenfassend würde ich gerne die Diskussion aus prozesstechnischer Sicht führen und dann die hierfür notwendigen Status (möglichst wenige -> wenig Komplexität) implementieren. Also sollten wir vielleicht noch besprechen, wie konkret im Labor der Ablauf sein sollte, wie mit den Proben umgegangen wird (PCR? etc.).

**Comment by ethylomat** [comment]
Also aus meiner Perspektive ist jetzt am wichtigsten, dass wir genug Tests schreiben für die aktuelle Version, bevor wir weitere grundlegende Änderungen durchführen.

**Comment by simon-anders** [comment]
Danke. Hier noch ein paar Überlegungen:

### zu WAIT und RECEIVED:

Also: Wenn das Sample im Labor eingeht und gescannt, wird der Status WAIT gesetzt. Ich nehme an, dein Lab-Interface macht das schon so.

Es wäre schön, dass in RECEIVED umzubennen, aber ist zu viel Refactoring-Arbeit, da wir die Dokumentation auch anpassen müssen. Du hast rect, da brauchen wir erst ein paar Tests.

Wenn WAIT der letzte Status ist, wird die Statusseite WAIT oder WAIT_LONG angezeigt. Wenn kein WAIT-Event existiert (also PRINTED der jüngste Status ist), dann wir die Meldung angezeigt, das die probe noch nicht da ist. Diese Seite sollte dann wohl tets-PRINTED.html heissen. Stimmt das so?

(Haben wir überhaput PRINTED? Oder ist das ein INFO-Event?)

### zu SENT_TO_PCR

Das war nicht als Status gemeint, sondern nur ein "INFO"-Event. WIr können das "sent to PCR" also in das Comment-Feld schreiben. 

Ich frage mich nur, ob es nicht nützlich wäre, das INFO-Event etwas mehr zu strukturieren, so dass wir dann nicht später Freitext parsen müssen.

### zu NO_PCR

Das soltle auch ein Info-Event sein. Du hast recht, es wirkt falsch, positive oder unklare Samples nicht zur PCR zu schicken. Aber wir haben manchmal nicht genug PCR-Kapazität, und dann muss das zumindest irgendwie dokumentiert werden.

Alternativ-Vorschlag: Ein Status SPECIAL, der einfach anzeigt, dass füë dieses Sample keine normale Resultat-Seite angezeigt werden soll, sondern ein Hinweis wie: Diese Probe ist ein Sonderfall. Wenn Sie ein normaler Proband sind und das sehen, dann ist was falsch gelaufen.

**Comment by simon-anders** [comment]
Sagst du mir bitte noch schnell, was UNDEFINED und ERROR genau sind, damit ich die Seite richtig schreibe?

**Comment by ethylomat** [comment]
ERROR sind bekannte Fehler, die beschrieben sind. UNDEFINED sind Fehler, die keine Beschreibung haben (insbesondere ist UNDEFINED auch ein eigener Status).

**Comment by simon-anders** [comment]
Closing this issue as it is superseded by Issue #164
