### ISSUE TITLE
Improve status flow of consent/given barcode 

### ISSUE THREAD

**Issue by ethylomat** [anders-biostat/covid-test-web-site#81]
At this moment they are simply passed as session parameters. Consent should be removed if page is left.

**Comment by simon-anders** [comment]
@alexey0308 Please have a look at that one. 

Imagine that two people from the same household want to register their sample, one after the other, on the same computer. We need to make sure that both are asked for consent. I'm not sure whether this is always the case right now. Could you check, please?

**Comment by simon-anders** [comment]
@AMueller92 this is fixed, right?

**Comment by AMueller92** [comment]
@simon-anders Yes this can be closed
