### ISSUE TITLE
Migration from papagei: update works properly?

### ISSUE THREAD

**Issue by simon-anders** [anders-biostat/covid-test-web-site#87]
A sample has been updated 1 h ago from "LAMPINC" to "PCRPOS" on papagei. This cannot yet be seen on the new production server. Is the mirroring active? Do updates get propagated properly?

**Comment by ethylomat** [comment]
Problem ist, dass der cronjob scheinbar ein memory-leak darstellt. Hab den jetzt sicherheitshalber abgestellt.

**Comment by ethylomat** [comment]
Grund dafür ist nicht bekannt. Aber irgendwie wird der Speicher hier nicht wieder freigegeben.

**Comment by simon-anders** [comment]
Problem has been solved end of November,.
